:PROPERTIES:
:ID:       e6e68b6d-bdee-4fdd-8000-f4e1896cb5fa
:END:
#+title: Analytical Reading
#+options: toc:nil num:nil
#+filetags: :todo:

First [[id:364b5089-0e7c-4160-95f6-40ef1ab467ac][Learn what a book is about before reading it]] by applying [[id:f475a741-2ea4-4eca-81db-bcedbe626342][Inspectional Reading]]

Wees een [[id:d64fe48f-5b63-4d3f-be0a-a6973a4562e1][kritisch lezer]]

Je vraagt niet aleen 'waar gaat het boek over' je vraagt 'wat is de bedoeling van de auteur'.
Omdat boven tafel te krijgen leg je de achterliggende structuur, de opbouw van het boek, bloot.

Als je het begrijpt kun je dit tegen iemand (jezelf) in een paar woorden/zinnen vertellen.

* I. The First Stage of Analytical Reading: Rules for Finding What a Book Is About

De eerste stap van [[id:f475a741-2ea4-4eca-81db-bcedbe626342][Inspectional Reading]], Systematic Skimming or Pre-reading, is een voorbereiding op het achterhalen waar een boek over gaat.

1. Classify the book according to kind and subject matter.
2. State what the whole book is about with the utmost brevity.
3. Enumerate its major parts in their order and relation, and outline
these parts as you have outlined the whole.
4. Define the problem or problems the author is trying to solve.

* II. The Second Stage of Analytical Reading: Rules for Interpreting a Book’s Contents

De tweede stap van [[id:f475a741-2ea4-4eca-81db-bcedbe626342][Inspectional Reading]], oppervlakkig lezen, is een voorbereiding op het interpreteren van het boek.


5. Come to terms with the author by interpreting his key words.
6. Grasp the author’s leading propositions by dealing with his most important sentences.
7. Know the author’s arguments, by finding them in, or constructing them out of, sequences of sentences.
8. Determine which of his problems the author has solved, and which he has not; and as of the latter, decide which the author knew he had failed to solve.

* III. The Third Stage of Analytical Reading: Rules for Criticizing a Book as a Communication of Knowledge

** A. /General Maxims of Intellectual Etiquette/

9. Do not begin criticism until you have completed your outline and your interpretation of the book. (Do not say you agree, disagree, or suspend judgment, until you say "I understand.")
10. Do not disagree disputatiously or contentiously.
11. Demonstrate that you recognize the difference between knowledge and mere personal opinion by presenting good reasons for any critical

** B. /Special Criteria for Points of Criticism/

12. Show wherein the author is uninformed.
13. Show wherein the author is misinformed.
14. Show wherein the author is illogical.
15. Show wherein the author’s analysis or account is incomplete.

Note:
Of these last four, the first three are criteria for disagreement. Failing
in all of these, you must agree, at least in part, although you may
suspend judgment on the whole, in the light of the last point.
