:PROPERTIES:
:ID:       db79a69b-b764-4a9f-b74e-598b64572166
:END:
#+title: Maak gedrag aantrekkelijk om een gewoonte te vormen

Als je een (gewenst) gedrag aantrekkelijk maakt zul je sneller geneigd zijn het te doen en is de kans veel groter dat je het een gewoonte maakt.

Je kunt gedrag wat je zou moeten doen koppelen aan gedrag wat je zou willen doen en dat [[id:6e37980e-254d-4be5-952c-10ed51475d50][gedrag allemaal stapelen op een bestaande gewoonte]].

+ Als [een bestaande gewoonte] doe ik [gewoonte die nodig is] en daarna doe ik [gewoonte die ik wil]

+ 's ochtends als ik de bakjes voor de kinderen gemaakt hebt, ruim ik de vaatwasser uit en ga ik lezen of computeren.
+ 's avonds als de tafel is afgeruimd, ruim ik de vaatwasser in, was ik de pannen, dek ik het aanrecht, en ga ik lezen of computeren.


+ [[id:eda58a0c-94c2-4631-84e9-2b7ff470d826][Aantrekkelijk maken. Plezier van anticipatie. De verwachting van een beloning zet ons aan tot actie.]]
+ [[id:617383aa-3456-4bee-bcc9-58f2ae7a5f95][Bundelen van een gewoonte die je nodig hebt met een huidige (die je wilt) verbind ze beide zodat je ze beide gaat doen.]]
