:PROPERTIES:
:ID:       a759965f-eb7d-4c01-9585-026ad0133472
:END:
#+title: Gesprek rabobank - maart 2022

- tags :: [[id:74dc6320-a69b-4fb3-a2dd-1f65b1d31fe4][Administratie]]

* Over werken in frankrijk

werken met bruto salaris, en silvia doet aangifte in frankrijk ...

* Salaris bruto

rekenen altijd zonder bonus
we moeten wel even DUO aflossen

Marcel 65.707
Silvia

Leen capaciteit: 460.620
1.751 per maand

Op 1 inkomen 330k

* Verhuizen

Woning die we gaan zien: 650

Geschatte waarde van wonig -> 572 obv laats verkocht.
Rekenen met 575k

We houden het spaar kapitaal 50k?

overwaarde 251k kan bij 460k -> 711

met spaar er in -> 763

kan ook met overwaarde van 303k als we eerst spaar kapitaal gebruiken om af te lossen.

* Verbouwen

Kijken dan alleen naar leen capiciteit.

*opties*
- verbouwen
- opbouwen
- verduurzamen

*wat*
- badkamer
- houten dueren
- vloer, schilderen, stucen
- cooker
- aanrechtblad

* Benodigd

taxatie rapport 750
desktop taxatie 85
oversluiten 1700
notaris 750 - besparen we omdat hypotheek is ingeschreven voor 400k


* Overbruggings hypotheek

is lager dan gewone hypotheek
deze hypotheek kun je gebruiken om eerst een woning te kopen en an je eigen verkopen

Moeten we echt gaan taxeren want huidige wning lijkt 585 online taxatie

* Voorbeeld

 7ton kopen
 718 hypotheek
 393 overwaarde

 415.450 wordt dan hypotheek

 bruto maandlasten 1.175

* Bij verbouwen

ongeveer 268 euro meer maandlasten

https://www.rabobank.nl/particulieren/hypotheek/hypotheekrente

* Vragen

- oversluiten en wel/niet spaardeel weg waarom/hoe?
- alles wat je nieuw in hypotheek opneemt mag je weer opnieuw 30jaar rente terug.
- bij rabobank blijft aflossingvrij
